export type EmployeeInfo = {
  headshotURL: string;
  name: string;
  title: string;
  ext: number;
  email: string;
  assistant: string;
  duties: string[];
};

export const employees: EmployeeInfo[] = [
  {
    headshotURL: "/haghighi.jpg",
    name: "Saideh Haghighi Khochkhou",
    title: "Operations Officer",
    ext: 41336,
    email: "haghighs@hsd.k12.or.us",
    assistant: "Emmanuel Moncada",
    duties: [],
  },
  {
    headshotURL: "/petersond.jpg",
    name: "Dave Peterson",
    title: "Executive Director of Facilities",
    ext: 41322,
    email: "petersod@hsd.k12.or.us",
    assistant: "Sydney Larrison",
    duties: [],
  },
  {
    headshotURL: "/hicksl.jpg",
    name: "Lisa Hicks",
    title: "Supervisor - Facilities & Maintenance",
    ext: 41332,
    email: "hicksl@hsd.k12.or.us",
    assistant: "Sydney Larrison",
    duties: [],
  },
  {
    headshotURL: "/moncadae.jpg",
    name: "Emmanuel Moncada",
    title: "Technology Integration",
    ext: 60424,
    email: "moncadae@hsd.k12.or.us",
    assistant: "",
    duties: [
      "CPR & First Aid Classes",
      "HSTAT/SIRC Forms",
      "Vector Training Platform Support",
    ],
  },
  {
    headshotURL: "/larrisons.jpg",
    name: "Sydney Larrison",
    title: "Department Admin Support 3",
    ext: 41321,
    email: "larrisos@hsd.k12.or.us",
    assistant: "",
    duties: [
      "District-wide inspections",
      "Facilities & TSSF Purchasing",
      "Graduation/HSD Festival",
      "Summer Crew",
      "Teacher Moves",
    ],
  },
  {
    headshotURL: "/rayborns.jpg",
    name: "Summer Rayborn",
    title: "Dept. Admin Support 2",
    ext: 41346,
    email: "rayborns@hsd.k12.or.us",
    assistant: "",
    duties: ["Incident IQ Facilities Work Order Tickets"],
  },
  {
    headshotURL: "/riosa.jpg",
    name: "Adela Rios",
    title: "Manager - Emergency and Disaster Preparedness",
    ext: 41327,
    email: "riosa@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Fire/Earthquake compliance",
      "Safety Plans & Monthly Document Reviews and questions",
      "SRP (Standard Response Protocol",
      "Reunification",
      "Strike Teams",
      "Student Incident Reports via Vector Incident Tracking",
      "Vector Compliance",
      "AED Support",
      "Evac Chair Support",
      "Crossing Gaurd Supplies",
    ],
  },
  {
    headshotURL: "/yellandj.jpg",
    name: "Jordan Yelland",
    title: "Supervisor - Electrical Systems",
    ext: 60429,
    email: "yellandj@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Lighting Outages",
      "Power Outages",
      "Tripped Breakers", 
      "Elevators", 
      "Damaged/Loose Wiring", 
      "Generators",
      "Solar Generation Issues"
    ],
  },
  {
    headshotURL: "/hockingm.jpg",
    name: "Mia Hocking",
    title: "Manager - Resource Conservation",
    ext: 41324,
    email: "hockinmi@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Building Performance Management (Energy Star Cert.",
      "Curriculum & Classroom Support re: Resource Conservation",
      "Oregon Green Schools",
      "Waste Management",
      "Recycling Programs",
      "Surplus Supplies",
      "Equiptment and Teacher Moves",
    ],
  },
  {
    headshotURL: "/ericksonl.jpg",
    name: "Lisa Erickson",
    title: "Manager - Security Services",
    ext: 41325,
    email: "ericksli@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Law Enforcement Liaison/School Resource Officer Contacts",
      "Threat Assessments/Sexual Incident Response Committee (SIRC's)",
      "Public Safety Issues",
      "Campus/Night Security Management",
      "Lockout/Lockdown Drills",
      "Trespassings",
      "School Traffic Flow assistance",
    ],
  },
  {
    headshotURL: "/salmeronh.png",
    name: "Hugo Salmeron",
    title: "Specialist - Public Safety Systems",
    ext: 41344,
    email: "salmeroh@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Access Control System",
      "Regular School Day Door Schedules",
      "Camera System",
      "Video Requests",
      "Intrusion Alarm System",
      "Radios",
      "Lockout/Lockdown Drills",
      "Contractors",
      "Keys",
    ],
  },
  {
    headshotURL: "/wenzloffw.jpg",
    name: "Will Wenzloff",
    title: "Supervisor - Environmental Health & Safety",
    ext: 41345,
    email: "wenzlofw@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Asbestos",
      "District Grounds",
      "Indoor Air Quality",
      "Integrated Pest Management (IPM)",
      "Lead Testing",
      "Playground Safety",
      "Radon Testing",
    ],
  },
  {
    headshotURL: "/larar.jpg",
    name: "Ray Lara",
    title: "Supervisor - Custodial Services",
    ext: 41338,
    email: "larar@hsd.k12.or.us",
    assistant: "Sandra Heredia",
    duties: [
      "Custodial: Oversee daily operations",
      "Hiring",
      "Investigation Support",
      "Policies & Procedures",
      "Custodian Training & Support",
      "Custodial Supply Orders",
      "Oversee Facilities District Warehouse",
      "Evaluation Support",
      "Site visits",
    ],
  },
  {
    headshotURL: "/roedeln.jpg",
    name: "Nate Roedel",
    title: "Executive Director of Nutrition Services",
    ext: 41461,
    email: "roedeln@hsd.k12.or.us",
    assistant: "",
    duties: [],
  },
  {
    headshotURL: "/hatfieldc.jpg",
    name: "Carol Hatfield",
    title: "Executive Director of Transportation",
    ext: 41100,
    email: "hatfielc@hsd.k12.or.us",
    assistant: "",
    duties: [],
  },
  {
    headshotURL: "/heredias.jpg",
    name: "Sandra Heredia",
    title: "Dept. Admin Support 3 - Custodial",
    ext: 41331,
    email: "heredias@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Custodial: Absences/Substitute Coverage",
      "Building Coverage for Events",
      "Overtime Scheduling",
      "ePARs",
      "Uniform Shirts",
      "Cintas",
      "Custodial Supplies Invoice Processing",
      "SDS Sheets Upload",
      "Custodial Exception Timesheets",
    ],
  },
  {
    headshotURL: "/perryl.jpg",
    name: "Laura Perry",
    title: "Supervisor - Nutrition Services",
    ext: 41460,
    email: "perryl@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Supper Program",
      "Catering",
      "Support kitchens of CHS/HHS Feeder Schools",
      "Headstart/Pre-K Programs",
    ],
  },
  {
    headshotURL: "/wildenborgj.jpg",
    name: "Jason Wildenborg",
    title: "Manager - Transportation",
    ext: 41114,
    email: "wildenbj@hsd.k12.or.us",
    assistant: "",
    duties: ["Support North Terminal Staff & Oversee Daily Operations", "Shop"],
  },
  {
    headshotURL: "/petrickr.jpg",
    name: "Rian Petrick",
    title: "Director of Extracurricular Services & Athletics",
    ext: 41333,
    email: "petrickr@hsd.k12.or.us",
    assistant: "",
    duties: [
      "After School Athletics & Activities - ES/MS",
      "Liaison for Hillsboro Parks & Rec",
      "STEAM Coach",
      "Outdoor School",
      "Coordinates with HS Athletic Directors & Activities Coordinators (OSAA)",
    ],
  },
  {
    headshotURL: "/drolettey.jpg",
    name: "Yvette Drolette",
    title: "Supervisor - Nutrition Services",
    ext: 41473,
    email: "droletty@hsd.k2.or.us",
    assistant: "",
    duties: [
      "USDA Food Programs",
      "Food Allergy Meal Accommodations",
      "Menu Information",
      "Support Kitchens of GHS/LHS feeder Schools",
      "Summer Meal Program",
      "After School Snacks"
    ],
  },
  {
    headshotURL: "/fornshellm.jpg",
    name: "Mike Fornshell",
    title: "Manager - Transportation",
    ext: 41111,
    email: "fornshem@hsd.k2.or.us",
    assistant: "",
    duties: ["Support Main Terminal Staff & Oversee Daily Operation"],
  },
  {
    headshotURL: "/mcmilland.jpg",
    name: "Denise McMillan",
    title: "Dept. Admin Support 3 - Facilities Use, Athletics & Activities",
    ext: 41343,
    email: "mcmillad@hsd.k2.or.us",
    assistant: "",
    duties: [
      "Athletics/Activities Stipends",
      "Door Schedules for After-hours & Weekends",
      "Facilitron Access/Reservations",
      "Field Light Schedules",
    ],
  },
  {
    headshotURL: "/turcottej.jpg",
    name: "Jon Turcotte",
    title: "Supervisor - Nutrition Services Warehouse & Distribution",
    ext: 41335,
    email: "turcottj@hsd.k12.or.us",
    assistant: "",
    duties: [
      "Maintenance of Kitchen Equipment",
      "Coordinate Nutrition Services Delivery Fleet",
      "Fridge & Freezer Security Alarm",
      "Vending Machine Management",
    ],
  },
  {
    headshotURL: "/mcfallsd.jpg",
    name: "Debbie McFalls",
    title: "Supervisor - Transportation",
    ext: 41116,
    email: "mcfallsd@hsd.k2.or.us",
    assistant: "",
    duties: [
      "Glencoe/Hilhi Feeders: Gen Ed & Sped",
      "Training",
      "Bus Recording & Safety",
      "Bus Referrals",
    ],
  },
  {
    headshotURL: "/morenol.jpg",
    name: "Leticia Moreno",
    title: "Dept. Admin Support 1",
    ext: 41337,
    email: "morenol@hsd.k2.or.us",
    assistant: "",
    duties: ["Grant Projects", "ES/MS Program Athletics/Activities"],
  },
  {
    headshotURL: "/petitte.jpg",
    name: "Elizabeth Petitt",
    title: "Specialist - Nutrition Services",
    ext: 60645,
    email: "petitte@hsd.k12.or.us",
    assistant: "",
    duties: ["After School Supper Program (CACFP)"],
  },
  {
    headshotURL: "/reeset.jpg",
    name: "Todd Reese",
    title: "Supervisor - Transportation",
    ext: 41131,
    email: "reeset@hsd.k2.or.us",
    assistant: "",
    duties: [
      "Century/Liberty Feeders: Gen Ed & Sped",
      "Training",
      "Bus Recording & Safety",
      "Bus Referrals",
    ],
  },
];
